name: networq:holacracy
description: Holacracy types
license: MIT

dependencies:
  networq:core: latest
  networq:organization: latest

navNodes:
  - networq:holacracy:acme

widgets:
  roleGuide:
    type: networq:holacracy:role
    hook: reports
    label: Role guide
    
  circleProperties:
    type: networq:holacracy:circle
    hook: properties
    label: Circle properties

  circleRolesTab:
    type: networq:holacracy:circle
    hook: tabs
    label: Roles

  partnerRolesTab:
    type: networq:holacracy:partner
    hook: tabs
    label: Roles

  circleCirclesTab:
    type: networq:holacracy:circle
    hook: tabs
    label: Sub Circles

  roleAccountabilitiesTab:
    type: networq:holacracy:role
    hook: tabs
    label: Accountabilities
  
  roleAssignmentsTab:
    type: networq:holacracy:role
    hook: tabs
    label: Assignments

  roleProperties:
    type: networq:holacracy:role
    hook: properties
    label: Role properties